__include__: [
  '../dataset/coco_detection.yml',
  '../runtime.yml',
  './include/dataloader.yml',
  './include/optimizer.yml',
  './include/rtdetrv2_r50vd.yml',
]


output_dir: ./output/rtdetrv2_r18vd_120e_coco

#model: RTDETR_freezebackbone_by_epoch

RTDETR:
  backbone: UniRepLKNet
  encoder: Slim_neck_C3
  decoder: RTDETRTransformerv2


RTDETRTransformerv2:
  num_layers: 3


epoches: 200

optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: 117
  collate_fn:
    scales: ~